package com.mbpt.peertutoringplatform.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(name = "Classroom", description = "A data model representing a classroom in the platform")
public class ClassRoomDTO {

    @JsonProperty("class_room_id")
    @Schema(description = "Unique identifier of the classroom. Automatically generated by the system", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer classRoomId;

    @NotBlank(message = "Classroom title must not be blank")
    @JsonProperty("title")
    @Schema(description = "The official name of the classroom, indicating the core subject matters or skills covered.", example = "CISSP Exam Prep", requiredMode = Schema.RequiredMode.REQUIRED)
    private String title;

//    @NotNull(message = "Enrolled student count must not be null")
    @JsonProperty("enrolled_student_count")
    @Schema(description = "Total number of students enrolled in the classroom", example = "30", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer enrolledStudentCount;

    @NotBlank(message = "Class image URL must not be blank")
    @JsonProperty("class_image")
    @Schema(description = "Image URL for the classroom", example = "http://example.com/classroom.jpg")
    private String classImage;

    @JsonProperty("mentor")
    @Schema(description = "Mentor assigned to this classroom")
    private MentorDTO mentorDTO;
}
