package com.mbpt.peertutoringplatform.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.mbpt.peertutoringplatform.common.Constants;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(name = "Session", description = "A data model representing a academic session in the platform")
public class SessionDTO {
    @JsonProperty("session_id")
    @Schema(description = "Unique identifier of the session. Automatically generated by the system", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer sessionId;

    @NotNull(message = "Session status must not be null")
    @JsonProperty("session_status")
    @Schema(description = "Current status of the session after the student schedules it. Possible values: PENDING, ACCEPTED, COMPLETED.", example = "PENDING", requiredMode = Schema.RequiredMode.REQUIRED)
    private Constants.SessionStatus sessionStatus;

    @NotNull(message = "Student must not be null")
    @JsonProperty("student")
    @Schema(description = "Student who is attending the session", requiredMode = Schema.RequiredMode.REQUIRED)
    private StudentDTO studentDTO;

    @NotNull(message = "Classroom must not be null")
    @JsonProperty("class_room")
    @Schema(description = "Classroom associated with the session", requiredMode = Schema.RequiredMode.REQUIRED)
    private ClassRoomDTO classRoomDTO;

    @NotNull(message = "Mentor must not be null")
    @JsonProperty("mentor")
    @Schema(description = "Mentor assigned to conduct the session", requiredMode = Schema.RequiredMode.REQUIRED)
    private MentorDTO mentorDTO;

    @NotBlank(message = "Topic must not be blank")
    @JsonProperty("topic")
    @Schema(description = "The specific topic covered during the session", example = "Introduction to Cloud Computing", requiredMode = Schema.RequiredMode.REQUIRED)
    private String topic;

    @NotNull(message = "Start time must not be null")
    @JsonProperty("start_time")
    @Schema(description = "Start time of the session in ISO-8601 format", example = "2025-08-01T09:00:00Z", requiredMode = Schema.RequiredMode.REQUIRED)
    private Instant startTime;

    @NotNull(message = "End time must not be null")
    @JsonProperty("end_time")
    @Schema(description = "End time of the session in ISO-8601 format", example = "2025-08-01T11:00:00Z", requiredMode = Schema.RequiredMode.REQUIRED)
    private Instant endTime;
}
