package com.mbpt.peertutoringplatform.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(name = "Student", description = "A data model representing a student in the platform")
public class StudentDTO {
    @JsonProperty("student_id")
    @Schema(description = "Unique identifier of the student. Automatically generated by the system", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer studentId;

    @NotBlank(message = "Clerk student ID must not be blank")
    @JsonProperty("clerk_student_id")
    @Schema(description = "Unique identifier of the student. Automatically generated by the authentication system", example = "ert8d7qtdy6h", accessMode = Schema.AccessMode.READ_ONLY)
    private String clerkStudentId;

    @NotBlank(message = "First name must not be blank")
    @JsonProperty("first_name")
    @Schema(description = "First name of the student", example = "Daniel", requiredMode = Schema.RequiredMode.REQUIRED)
    private String firstName;

    @NotBlank(message = "Last name must not be blank")
    @JsonProperty("last_name")
    @Schema(description = "Last name of the student", example = "Andrew", requiredMode = Schema.RequiredMode.REQUIRED)
    private String lastName;

    @NotBlank(message = "Email must not be blank")
    @Email(message = "Email must be valid")
    @JsonProperty("email")
    @Schema(description = "Email of the student", example = "daniel@gmail.com", requiredMode = Schema.RequiredMode.REQUIRED)
    private String email;

    @Pattern(regexp = "^\\+[1-9]\\d{6,14}$", message = "Phone number must be valid E.164 format. Must start with '+' followed by 7-15 digits only.")
    @NotBlank(message = "Phone number must not be blank")
    @JsonProperty("phone_number")
    @Schema(description = "Phone number of the student", example = "+15559876543", requiredMode = Schema.RequiredMode.REQUIRED)
    private String phoneNumber;

    @NotBlank(message = "Address must not be blank")
    @JsonProperty("address")
    @Schema(description = "Address of the student", example = "123 Elm St, Springfield, IL 62704, USA", requiredMode = Schema.RequiredMode.REQUIRED)
    private String address;

    @NotNull(message = "Age must not be null")
    @Min(value = 18, message = "Age must be at least 18")
    @JsonProperty("age")
    @Schema(description = "Age of the student and it must be at least 18", example = "23", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer age;
}
