package com.mbpt.peertutoringplatform.service;

import com.mbpt.peertutoringplatform.common.Constants;
import com.mbpt.peertutoringplatform.dto.SessionDTO;
import com.mbpt.peertutoringplatform.dto.SessionLiteDTO;

import java.util.List;

/**
 * Service interface for managing session-related operations.
 * This includes session creation, retrieving all sessions,
 * auditing session data, and generating mentor payment summaries.
 */
public interface SessionService {

    /**
     * Creates a new session with the given session details.
     *
     * @param sessionDTO the session data transfer object containing session details
     * @return the created {@link SessionDTO } with its generated ID and saved values
     */
    SessionLiteDTO createSession(SessionLiteDTO sessionDTO);


    /**
     * Retrieves all session records with student, mentor, and classroom details.
     *
     * @return a list of {@link SessionDTO} instances representing the sessions
     */
    List<SessionDTO> getAllSessions();


    /**
     * Retrieves all sessions by student Clerk ID.
     *
     * @param studentClerkId the ID for the student generated by Clerk, to retrieve all sessions of the student
     * @return a list of {@link SessionDTO} instances representing the sessions
     */
    List<SessionDTO> getAllSessionsByStudentClerkId(String studentClerkId);

    /**
     * Updates the status of an existing session
     *
     * @param sessionId     the ID of the session to update
     * @param sessionStatus the new status to set
     * @return a SessionDTO object representing the updated session
     */
    SessionDTO updateSessionStatus(Integer sessionId, Constants.SessionStatus sessionStatus);

}
