package com.mbpt.peertutoringplatform.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(name = "LiteSessionDTO", description = "A simplified data model representing a session with essential details for quick reference.")
public class SessionLiteDTO {
    @JsonProperty("session_id")
    @Schema(description = "Unique identifier of the session. Automatically generated by the system", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer sessionId;

    @NotNull(message = "Student ID must not be null")
    @JsonProperty("student_id")
    @Schema(description = "ID of the student who is attending the session", example = "1", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer studentId;

    @NotNull(message = "Classroom ID must not be null")
    @JsonProperty("class_room_id")
    @Schema(description = "ID of the classroom associated with the session", example = "1", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer classRoomId;

    @NotNull(message = "Mentor ID must not be null")
    @JsonProperty("mentor_id")
    @Schema(description = "ID of the mentor assigned to conduct the session", example = "1", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer mentorId;

    @NotBlank(message = "Topic must not be blank")
    @JsonProperty("topic")
    @Schema(description = "The specific topic covered during the session", example = "Introduction to Cloud Computing", requiredMode = Schema.RequiredMode.REQUIRED)
    private String topic;

    @NotNull(message = "Start time must not be null")
    @JsonProperty("start_time")
    @Schema(description = "Start time of the session in ISO-8601 format", example = "2025-08-01T09:00:00Z", requiredMode = Schema.RequiredMode.REQUIRED)
    private Instant startTime;

    @NotNull(message = "End time must not be null")
    @JsonProperty("end_time")
    @Schema(description = "End time of the session in ISO-8601 format", example = "2025-08-01T11:00:00Z", requiredMode = Schema.RequiredMode.REQUIRED)
    private Instant endTime;
}
